-- Generated from Men (Singles Only) 2e00637c552080baac8bcf05fd599187_all.csv
-- Dataset: mens_singles_only_2e00637c552080baac8bcf05fd599187

begin;

delete from public.resources
where source_dataset = 'mens_singles_only_2e00637c552080baac8bcf05fd599187';

insert into public.resources (
  title,
  description,
  categories,
  tags,
  sub_tags,
  eligibility,
  hours,
  contact_phone,
  contact_email,
  contact_website,
  location,
  coordinates,
  featured,
  urgency,
  status,
  return_comment,
  tips,
  call_script,
  domain,
  resource_type,
  population_tags,
  accessibility_tags,
  service_tags,
  availability_type,
  beds,
  intake_type,
  source_dataset,
  source_record_id
)
values
  (
    'A Safe Haven Foundation',
    'Men''s single-adult emergency shelter in Chicago. Availability: 24hr. Capacity: 72 beds.',
    array['Housing']::text[],
    array['shelter', 'emergency shelter', 'single adults', 'men']::text[],
    array['tonight', 'short-term']::text[],
    'Single adult men seeking shelter.',
    '24hr',
    '(312) 758-0291 (PM) or / (773) 435-8300',
    null,
    null,
    '2750 W Roosevelt Rd, Chicago, IL 60608-1048, United States',
    null,
    false,
    1,
    'approved',
    null,
    '{}'::text[],
    'Say: Hi, I''m looking for a men''s shelter bed tonight. Do you have availability and what is the intake process?',
    'housing',
    'emergency_shelter',
    array['men', 'single_adults']::text[],
    '{}'::text[],
    array['emergency_shelter', 'men', 'shelter', 'single_adults']::text[],
    'twenty_four_hours',
    72,
    'call_first',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187-001-a-safe-haven-foundation'
  ),
  (
    'Cornerstone Community Outreach Naomi',
    'Men''s single-adult emergency shelter in Chicago. Availability: 24hr. Capacity: 28 beds.',
    array['Housing']::text[],
    array['shelter', 'emergency shelter', 'single adults', 'men']::text[],
    array['tonight', 'short-term', 'ground-floor']::text[],
    'Single adult men seeking shelter.',
    '24hr',
    '(773) 506-6396 x 17 / (773) 907-3480',
    null,
    null,
    '5352 N Kenmore Ave, Chicago, IL 60640-2463, United States',
    null,
    false,
    1,
    'approved',
    null,
    array['No elevator', 'Not wheelchair accessible', 'Shelter overnight 2nd floor', 'During day 1st floor', 'Dining 1st floor', 'Open dorm single bed']::text[],
    'Say: Hi, I''m looking for a men''s shelter bed tonight. Do you have availability and what is the intake process?',
    'housing',
    'emergency_shelter',
    array['men', 'single_adults']::text[],
    array['ground_floor']::text[],
    array['dorm_style', 'emergency_shelter', 'men', 'shelter', 'single_adults', 'single_beds']::text[],
    'twenty_four_hours',
    28,
    'call_first',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187-002-cornerstone-community-outreach-naomi'
  ),
  (
    'Fransciscan Outreach Association Annex',
    'Men''s single-adult emergency shelter in Chicago. Availability: Overnight. Capacity: 70 beds.',
    array['Housing']::text[],
    array['shelter', 'emergency shelter', 'single adults', 'men']::text[],
    array['tonight', 'short-term']::text[],
    'Single adult men seeking shelter.',
    'Overnight | Opens at 6PM and discharges at 6AM',
    '(773) 533-4595',
    null,
    null,
    '200 S Sacramento Blvd, Chicago, IL 60612-2716, United States',
    null,
    false,
    1,
    'approved',
    null,
    array['Single cot', 'Walk ins allowed', 'Opens at 6PM and discharges at 6AM']::text[],
    'Say: Hi, I''m looking for a men''s shelter bed tonight. Do you have availability and what is the intake process?',
    'housing',
    'emergency_shelter',
    array['men', 'single_adults']::text[],
    '{}'::text[],
    array['emergency_shelter', 'men', 'shelter', 'single_adults', 'walk_in']::text[],
    'overnight',
    70,
    'walk_in',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187-003-fransciscan-outreach-association-annex'
  ),
  (
    'Northside Housing and Supportive Services',
    'Men''s single-adult emergency shelter in Chicago. Availability: 24hr. Capacity: 70 beds.',
    array['Housing']::text[],
    array['shelter', 'emergency shelter', 'single adults', 'men']::text[],
    array['tonight', 'short-term', 'wheelchair', 'ground-floor']::text[],
    'Single adult men seeking shelter.',
    '24hr',
    '(773) 754-7607',
    null,
    null,
    '7464 N Clark St, Chicago, IL 60626-1620, United States',
    null,
    false,
    1,
    'approved',
    null,
    array['Wheelchair accessible', '(1) main floor', '(2) people per room']::text[],
    'Say: Hi, I''m looking for a men''s shelter bed tonight. Do you have availability and what is the intake process?',
    'housing',
    'emergency_shelter',
    array['men', 'single_adults']::text[],
    array['ground_floor', 'wheelchair_accessible']::text[],
    array['accessible', 'emergency_shelter', 'men', 'shelter', 'single_adults']::text[],
    'twenty_four_hours',
    70,
    'call_first',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187-004-northside-housing-and-supportive-services'
  ),
  (
    'Olive Branch Mission Lamplight #1 Single Men',
    'Men''s single-adult emergency shelter in Chicago. Availability: 24hr. Capacity: 110 beds.',
    array['Housing']::text[],
    array['shelter', 'emergency shelter', 'single adults', 'men']::text[],
    array['tonight', 'short-term']::text[],
    'Single adult men seeking shelter.',
    '24hr',
    '(773) 476-6200 x10, x18',
    null,
    null,
    '6310 S Claremont Ave, Chicago, IL 60636-2439, United States',
    null,
    false,
    1,
    'approved',
    null,
    array['No elevator', 'Not wheelchair accessible', 'Shelter on 2nd floor', 'Bunk beds', 'Kitchen on 1st floor', 'No suitcases']::text[],
    'Say: Hi, I''m looking for a men''s shelter bed tonight. Do you have availability and what is the intake process?',
    'housing',
    'emergency_shelter',
    array['men', 'single_adults']::text[],
    '{}'::text[],
    array['bunk_beds', 'emergency_shelter', 'men', 'shelter', 'single_adults']::text[],
    'twenty_four_hours',
    110,
    'call_first',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187-005-olive-branch-mission-lamplight-1-single-men'
  ),
  (
    'Olive Branch Mission Lamplight #2 Single Men',
    'Men''s single-adult emergency shelter in Chicago. Availability: 24hr. Capacity: 50 beds.',
    array['Housing']::text[],
    array['shelter', 'emergency shelter', 'single adults', 'men']::text[],
    array['tonight', 'short-term']::text[],
    'Single adult men seeking shelter.',
    '24hr',
    '(773) 660-8625',
    null,
    null,
    '544 W 123rd St, Chicago, IL 60628-6443, United States',
    null,
    false,
    1,
    'approved',
    null,
    array['No elevator', 'Not wheelchair accessible', 'Shelter on 2nd floor', 'Bunk beds', 'Kitchen on 1st floor', 'No suitcases']::text[],
    'Say: Hi, I''m looking for a men''s shelter bed tonight. Do you have availability and what is the intake process?',
    'housing',
    'emergency_shelter',
    array['men', 'single_adults']::text[],
    '{}'::text[],
    array['bunk_beds', 'emergency_shelter', 'men', 'shelter', 'single_adults']::text[],
    'twenty_four_hours',
    50,
    'call_first',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187-006-olive-branch-mission-lamplight-2-single-men'
  ),
  (
    'A Little Bit of Heaven',
    'Men''s single-adult emergency shelter in Chicago. Availability: Overnight. Capacity: 50 beds.',
    array['Housing']::text[],
    array['shelter', 'emergency shelter', 'single adults', 'men']::text[],
    array['tonight', 'short-term']::text[],
    'Single adult men seeking shelter.',
    'Overnight | Opens at 4pm and discharges at 8:30am',
    '(773) 660-8625',
    null,
    null,
    '11321 S Wentworth Ave, Chicago, IL 60628-4114, United States',
    null,
    false,
    1,
    'approved',
    null,
    array['No elevator', '4 floors', '1st floor dining', '2nd, 3d and 4th shelter (bunk beds)', 'Opens at 4pm and discharges at 8:30am']::text[],
    'Say: Hi, I''m looking for a men''s shelter bed tonight. Do you have availability and what is the intake process?',
    'housing',
    'emergency_shelter',
    array['men', 'single_adults']::text[],
    '{}'::text[],
    array['bunk_beds', 'emergency_shelter', 'men', 'shelter', 'single_adults']::text[],
    'overnight',
    50,
    'call_first',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187-007-a-little-bit-of-heaven'
  ),
  (
    'St. Leonard’s Ministry Men’s Interim Housing',
    'Men''s single-adult emergency shelter in Chicago. Availability: 24hr. Capacity: 36 beds. Returning citizens only.',
    array['Housing']::text[],
    array['shelter', 'emergency shelter', 'single adults', 'men']::text[],
    array['tonight', 'short-term']::text[],
    'Returning citizens only.',
    '24hr',
    '(312) 738-1414 x24',
    null,
    null,
    '2100 W Warren Blvd, Chicago, IL 60612-2310, United States',
    null,
    false,
    1,
    'approved',
    null,
    array['Returning citizens only', 'Returning citizens on pretrial probation, probation, parole, or have an assigned case worker through the court', 'No arson/sex offense allowed', 'Client’s parole or probation officer is supposed to facilitate in place of client']::text[],
    'Say: Hi, I''m looking for a men''s shelter bed tonight. Do you have availability and what is the intake process?',
    'housing',
    'emergency_shelter',
    array['men', 'single_adults']::text[],
    '{}'::text[],
    array['emergency_shelter', 'men', 'returning_citizens', 'shelter', 'single_adults']::text[],
    'twenty_four_hours',
    36,
    'referral',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187-008-st-leonard-s-ministry-men-s-interim-housing'
  ),
  (
    'Inner Voice (Pioneer House)',
    'Men''s single-adult emergency shelter in Chicago. Availability: 24hr. Capacity: 17 beds.',
    array['Housing']::text[],
    array['shelter', 'emergency shelter', 'single adults', 'men']::text[],
    array['tonight', 'short-term']::text[],
    'Single adult men seeking shelter.',
    '24hr',
    '(773) 921-5290',
    null,
    null,
    '4458 W Jackson Blvd, Chicago, IL 60624-2530, United States',
    null,
    false,
    1,
    'approved',
    null,
    array['No elevator', 'Not wheelchair accessible?', 'Shelter on 2nd floor', 'Single beds', 'Kitchen on 1st floor']::text[],
    'Say: Hi, I''m looking for a men''s shelter bed tonight. Do you have availability and what is the intake process?',
    'housing',
    'emergency_shelter',
    array['men', 'single_adults']::text[],
    '{}'::text[],
    array['emergency_shelter', 'men', 'shelter', 'single_adults', 'single_beds']::text[],
    'twenty_four_hours',
    17,
    'call_first',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187-009-inner-voice-pioneer-house'
  ),
  (
    'Inner Voice (Robert Johnson House)',
    'Men''s single-adult emergency shelter in Chicago. Availability: 24hr.',
    array['Housing']::text[],
    array['shelter', 'emergency shelter', 'single adults', 'men']::text[],
    array['tonight', 'short-term', 'wheelchair']::text[],
    'Single adult men seeking shelter.',
    '24hr',
    '(312) 994-4352',
    null,
    null,
    '8040 S Western Ave, Chicago, IL 60620-5936, United States',
    null,
    false,
    1,
    'approved',
    null,
    array['Has elevator', 'Wheelchair accessible', 'Shelter on 2nd floor', 'Shared rooms, single beds', 'Kitchen on 1st floor']::text[],
    'Say: Hi, I''m looking for a men''s shelter bed tonight. Do you have availability and what is the intake process?',
    'housing',
    'emergency_shelter',
    array['men', 'single_adults']::text[],
    array['elevator', 'wheelchair_accessible']::text[],
    array['accessible', 'emergency_shelter', 'men', 'shelter', 'single_adults', 'single_beds']::text[],
    'twenty_four_hours',
    null,
    'call_first',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187-010-inner-voice-robert-johnson-house'
  ),
  (
    'Breakthrough Urban Ministries',
    'Men''s single-adult emergency shelter in Chicago. Availability: 24hr, has a day center. Capacity: 30 beds.',
    array['Housing']::text[],
    array['shelter', 'emergency shelter', 'single adults', 'men']::text[],
    array['tonight', 'short-term', 'wheelchair', 'ground-floor']::text[],
    'Single adult men seeking shelter.',
    '24hr, has a day center',
    null,
    null,
    null,
    '402 N St Louis Ave, Chicago, IL 60624-1332, United States',
    null,
    false,
    1,
    'approved',
    null,
    array['Has elevator', 'Wheelchair accessible', 'Shelter on 1st floor', 'Dorm style single beds', 'Kitchen/restroom/shower on shelter floor']::text[],
    'Say: Hi, I''m looking for a men''s shelter bed tonight. Do you have availability and what is the intake process?',
    'housing',
    'emergency_shelter',
    array['men', 'single_adults']::text[],
    array['elevator', 'ground_floor', 'wheelchair_accessible']::text[],
    array['accessible', 'day_center', 'dorm_style', 'emergency_shelter', 'men', 'shelter', 'single_adults', 'single_beds']::text[],
    'twenty_four_hours',
    30,
    'call_first',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187-011-breakthrough-urban-ministries'
  ),
  (
    'Wholistic House',
    'Men''s single-adult emergency shelter in Chicago. Availability: 24hr. Capacity: 50 beds. Clients must be 35 or older.',
    array['Housing']::text[],
    array['shelter', 'emergency shelter', 'single adults', 'men']::text[],
    array['tonight', 'short-term', 'ground-floor']::text[],
    'Clients must be 35 or older.',
    '24hr',
    '(773) 699-8573',
    null,
    null,
    '7000 S Racine Ave, Chicago, IL 60636-3509, United States',
    null,
    false,
    1,
    'approved',
    null,
    array['No elevator', 'Not wheelchair accessible', 'Shelter 1st and 2nd floor', 'Bunk beds and single beds', 'Clients must be 35 or older']::text[],
    'Say: Hi, I''m looking for a men''s shelter bed tonight. Do you have availability and what is the intake process?',
    'housing',
    'emergency_shelter',
    array['men', 'single_adults']::text[],
    array['ground_floor']::text[],
    array['bunk_beds', 'emergency_shelter', 'men', 'shelter', 'single_adults', 'single_beds']::text[],
    'twenty_four_hours',
    50,
    'call_first',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187-012-wholistic-house'
  ),
  (
    'Freedom Center; Harbor Light',
    'Men''s single-adult emergency shelter in Chicago. Availability: Overnight. Capacity: 100 beds. Seasonally open or by DFSS request; closed.',
    array['Housing']::text[],
    array['shelter', 'emergency shelter', 'single adults', 'men']::text[],
    array['tonight', 'short-term']::text[],
    'Seasonal or DFSS-request placement may apply.',
    'Overnight | 6:30pm-8:30am M-F',
    '(312) 667-2204',
    null,
    null,
    '825 N Christiana Ave, Chicago, IL 60651-4110, United States',
    null,
    false,
    1,
    'approved',
    null,
    array['Seasonally open or by DFSS request; closed', '6:30pm-8:30am M-F', 'Weekends 24/7']::text[],
    'Say: Hi, I''m looking for a men''s shelter bed tonight. Do you have availability and what is the intake process?',
    'housing',
    'emergency_shelter',
    array['men', 'single_adults']::text[],
    '{}'::text[],
    array['emergency_shelter', 'men', 'shelter', 'single_adults']::text[],
    'overnight',
    100,
    'referral',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187-013-freedom-center-harbor-light'
  ),
  (
    'The Boulevard',
    'Men''s single-adult emergency shelter in Chicago. Availability: 24hr. Capacity: 46 beds. Acute medical conditions with 30-day supply (High blood pressure, diabetes, etc).',
    array['Housing']::text[],
    array['shelter', 'emergency shelter', 'single adults', 'men']::text[],
    array['tonight', 'short-term', 'wheelchair']::text[],
    'Clients must be able to care for themselves.',
    '24hr',
    '(773) 533-6013 x234 / or / Option 4',
    null,
    null,
    '3456 W Franklin Blvd, Chicago, IL 60624-1308, United States',
    null,
    false,
    1,
    'approved',
    null,
    array['Has elevator', 'Wheelchair accessible', 'Acute medical conditions with 30-day supply (High blood pressure, diabetes, etc)', '(4) persons to 1 room (single beds)', 'Dining in basement', 'The client must be able to care for him/herself (504-compliant)']::text[],
    'Say: Hi, I''m looking for a men''s shelter bed tonight. Do you have availability and what is the intake process?',
    'housing',
    'emergency_shelter',
    array['men', 'single_adults']::text[],
    array['elevator', 'wheelchair_accessible']::text[],
    array['accessible', 'emergency_shelter', 'men', 'shelter', 'single_adults', 'single_beds']::text[],
    'twenty_four_hours',
    46,
    'call_first',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187-014-the-boulevard'
  ),
  (
    'Brighstar YWLA',
    'Men''s single-adult emergency shelter in Chicago. Capacity: 212 beds.',
    array['Housing']::text[],
    array['shelter', 'emergency shelter', 'single adults', 'men']::text[],
    array['tonight', 'short-term']::text[],
    'Single adult men seeking shelter.',
    '',
    '(312) 402-6612',
    null,
    null,
    '2641 S Calumet Ave, Chicago, IL 60616-2901, United States',
    null,
    false,
    1,
    'approved',
    null,
    '{}'::text[],
    'Say: Hi, I''m looking for a men''s shelter bed tonight. Do you have availability and what is the intake process?',
    'housing',
    'emergency_shelter',
    array['men', 'single_adults']::text[],
    '{}'::text[],
    array['emergency_shelter', 'men', 'shelter', 'single_adults']::text[],
    null,
    212,
    'call_first',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187',
    'mens_singles_only_2e00637c552080baac8bcf05fd599187-015-brighstar-ywla'
  );

commit;
